### ISSUE TITLE
Dynamic re-configuration in the cluster

### ISSUE THREAD

**Issue by OlegKunitsyn** [evgenyigumnov/cblt#14]
The proxy should listen to K8S and Docker Swarm labels for dynamic re-configuration without restarts.  
Similar to https://github.com/lucaslorentz/caddy-docker-proxy
Flow: Cloudflare proxy -- mTLS --> Cblt proxy  -- labels --> services

**Comment by evgenyigumnov** [comment]
dublicate https://github.com/evgenyigumnov/cblt/issues/17 https://github.com/evgenyigumnov/cblt/issues/19
