### ISSUE TITLE
Guaranteed request delivery in LB mode

### ISSUE THREAD

**Issue by OlegKunitsyn** [evgenyigumnov/cblt#33]
Implement a mechanism in the CBLT proxy to ensure guaranteed delivery of incoming requests, with failover and retry when backends fail to respond.

- When a request arrives at the CBLT proxy, it should first attempt to forward the request to Backend 1.
- If Backend 1 does not respond within the `lb_timeout` period, the proxy retries the request up to `lb_retries` times.
- If Backend 1 is still unresponsive after the retries, the proxy forwards the request to Backend 2 based on the `lb_policy` algorithm.
- Backend 1 is marked as down and INFO log entry should be created.
- During the `lb_interval` period, the proxy should periodically check the status of Backend 1.
- If Backend 1 responds successfully during a check, it should be marked as up and INFO log entry should be created.
- If no backends are available, ERROR log entry should be created to escalate the failure.
- The proxy should periodically continue checking the status of the backends.

**Values**
- reliability by design
- auto-recovery
- less configuration parameters, `health_uri` not needed

**Comment by evgenyigumnov** [comment]
done but not merged in main
I will merge soon
